<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Robot properties -->
  <xacro:property name="wheel_diam" value="0.085"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_sep" value="0.18"/>
  <xacro:property name="caster_diam" value="0.04"/>
  <xacro:property name="lower_plate_diam" value="0.22"/>
  <xacro:property name="lower_plate_thk" value="0.01"/>
  <xacro:property name="upper_plate_diam" value="0.22"/>
  <xacro:property name="upper_plate_thk" value="0.008"/>
  <xacro:property name="plate_gap" value="0.08"/>
  <xacro:property name="m_lower" value="1.2"/>
  <xacro:property name="m_upper" value="0.8"/>
  <xacro:property name="m_wheel" value="0.15"/>
  <xacro:property name="m_cast" value="0.05"/>

  <!-- Derived values -->
  <xacro:property name="Rlower" value="${lower_plate_diam/2.0}"/>
  <xacro:property name="Rupper" value="${upper_plate_diam/2.0}"/>
  <xacro:property name="Rwheel" value="${wheel_diam/2.0}"/>
  <xacro:property name="Rcaster" value="${caster_diam/2.0}"/>

  <!-- Colors -->
  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="blue"><color rgba="0.1 0.2 0.8 1.0"/></material>
  <material name="green"><color rgba="0.1 0.6 0.2 1.0"/></material>
  <material name="black"><color rgba="0.05 0.05 0.05 1.0"/></material>

</robot>
